controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    swerve_steering_controller:
      type: position_controllers/JointGroupPositionController

simple_velocity_controller:
  ros__parameters:
    joints:
      - front_right_wheel_joint
      - front_left_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint

swerve_steering_controller:
  ros__parameters:
    joints:
      - steer_front_left_joint
      - steer_front_right_joint
      - steer_rear_left_joint
      - steer_rear_right_joint
